include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/codegen/**
    - lib/locale/**
    - lib/injection.config.dart

linter:
  rules:
    prefer_if_elements_to_conditional_expressions: false
