name: kayaya_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  graphql_flutter: ^4.0.0-beta
  scroll_bars_common: 2.0.0
  cached_network_image: ^2.2.0+1
  injectable: ^1.0.5
  get_it: ^5.0.1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  hydrated_bloc: ^6.1.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  equatable: ^1.2.5
  rxdart: ^0.24.1
  quiver: ^2.1.3
  shimmer: ^1.1.1
  logger: ^0.9.2
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  extended_nested_scroll_view: ^1.0.1
  url_launcher: ^5.5.1
  webview_flutter: ^0.3.22+1
  chewie:
    path: ../chewie
    # git:
    #   url: https://github.com/kono0514/chewie_extended.git
  flutter_custom_tabs: ^0.6.0
  flutter_widget_from_html_core: ^0.5.1+3
  # TODO: Switch to official version when this is merged:
  # https://github.com/itzmeanjan/intent/pull/38
  # https://github.com/itzmeanjan/intent/pull/37
  intent:
    git:
      url: https://github.com/kono0514/intent
  dynamic_widget: ^2.0.3
  carousel_slider: ^2.2.1
  algolia: ^0.1.7
  settings_ui: ^0.4.0
  flutter_local_notifications: ^1.4.4+4
  firebase_core: 0.5.0+1
  firebase_messaging: ^7.0.0
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.0+4
  modal_bottom_sheet: ^1.0.0+1
  pin_code_fields: ^6.0.1
  path_provider: ^1.6.14
  flutter_cache_manager: ^1.4.2
  flutter_auto_pip:
    path: ../flutter_auto_pip
    # git:
    #   url: https://github.com/kono0514/flutter-auto-pip.git
  package_info: ^0.4.3+2
  fl_chart: ^0.12.0
  flutter_xupdate:
    git:
      url: https://github.com/kono0514/flutter_xupdate
  dartz: ^0.9.2
  native_device_orientation: ^0.4.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^6.17.1
  # artemis:
  #   git:
  #     url: https://github.com/comigor/artemis.git
  #     ref: tojson-prefix-fix
  build_runner: ^1.10.1
  json_serializable: ^3.0.0
  mockito: ^4.1.3
  injectable_generator: ^1.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/google_dark.png
    - assets/logos/google_light.png
    - assets/logos/facebook.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: TR
  arb_dir: lib/locale/l10n
  output_dir: lib/locale/generated
  localizely:
    project_id: 3789b0db-4302-475e-949b-7c802138773b
